### PR TITLE
feat: using 'from' keyword as a dictonary key for SendParams Emails

### PR DESCRIPTION
**Pull request by pedroimpulcetto**
This is an option to have 'from' inside SendParams.

---

We also can define `_SendParamsType` inside Emails class to be inaccessible outside of the class.

---

Here are the [typing docs](https://docs.python.org/3/library/typing.html#typing.TypedDict) to help us to use 'from' as a dict key.

The functional syntax should also be used when any of the keys are not valid [identifiers](https://docs.python.org/3/reference/lexical_analysis.html#identifiers), for example because they are keywords or contain hyphens. Example:

```python
# raises SyntaxError
class Point2D(TypedDict):
    in: int  # 'in' is a keyword
    x-y: int  # name with hyphens

# OK, functional syntax
Point2D = TypedDict('Point2D', {'in': int, 'x-y': int})
```

### CODE REVIEW

**Comment by pedroimpulcetto** [comment]
@drish I guess this is going to help 🙏

**Comment by drish** [comment]
@pedroimpulcetto this is great, one caveat that I noticed though is that we lose the docstrings documentation on attributes (dict keys) when using function based TypedDicts ?

**Comment by pedroimpulcetto** [comment]
> @pedroimpulcetto this is great, one caveat that I noticed though is that we lose the docstrings documentation on attributes (dict keys) when using function based TypedDicts ?

Actually, class attributes don't allow docstring, only the class itself is allowed to have docstring following PEP-0257, even though it looks nice.
[PEP-0257](https://peps.python.org/pep-0257/) - Docstring
[Class Object](https://docs.python.org/3/tutorial/classes.html#class-objects)

We can do like this:
```python
class SendParams(_SendParamsType):
    """Class etc...

        Attributes:
            to (Union[str, List[str]]): List of email addresses to send the email to.
            subject (str): The subject of the email.
            ...
        """
```

What do you think?

**Comment by pedroimpulcetto** [comment]
let me know to close this PR

**Comment by drish** [comment]
@pedroimpulcetto since this PR removes support for sender and from_ im closing this PR but I will be introducing this change separately, since we need to support all the three options: `sender`, `from_` and `from`

**Pull request closed without merging**
