### PR TITLE
Resend API url Exposed as a configuration item

### PR DESCRIPTION
**Pull request by BenjaminX**

### CODE REVIEW

**Comment by BenjaminX** [comment]
@drish Hey, Can you help me review code and pass CI?

Configurable API URL addresses are used for Cloudflare work forwarding to avoid interference from the Great Firewall (GFW).

**Review by drish — APPROVED** [review]
@BenjaminX lgtm

**Comment by drish** [comment]
@BenjaminX I will merge this, but I will only release a new version in the next couple of days together with some new functionality that is coming in, would you mind using the main branch for a little while ?

**Comment by BenjaminX** [comment]
> @BenjaminX I will merge this, but I will only release a new version in the next couple of days together with some new functionality that is coming in, would you mind using the main branch for a little while ?

sure, follow you planning. Thx

**Pull request merged**
