### PR TITLE
Added __version__ in __init__.py

### PR DESCRIPTION
**Pull request by rosaboyle**

### CODE REVIEW

**Comment by drish** [comment]
hey @rosaboyle, you can use the `get_version` method that is already exported instead of accessing `__version__` directly.

**Comment by rosaboyle** [comment]
Why not use the standard procedure everyone uses?

**Comment by drish** [comment]
@rosaboyle you actually have a point and I changed my mind 👍, thanks for letting me know

**Review by drish — APPROVED** [review]

**Comment by rosaboyle** [comment]
👍

**Pull request merged**
